using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ThMEPWSS.Assistant
{
    static class FengKeys
    {
        public const string ThWRainSystemDiagramData = "qrjq0x";
        public const string ThRainSystemServiceContextData = "qrjq0y";
        public const string LinesGroupData = "qrjq0z";
        public const string qrjq1a = "qrjq1a";
        public const string qrjq1b = "qrjq1b";
        public const string qrjq1c = "qrjq1c";
        public const string qrjq1d = "qrjq1d";
        public const string qrjq1e = "qrjq1e";
        public const string qrjq1f = "qrjq1f";
        public const string qrjq1g = "qrjq1g";
        public const string qrjq1h = "qrjq1h";
        public const string qrjq1i = "qrjq1i";
        public const string qrjq1j = "qrjq1j";
        public const string qrjq1k = "qrjq1k";
        public const string qrjq1l = "qrjq1l";
        public const string qrjq1m = "qrjq1m";
        public const string qrjq1n = "qrjq1n";
        public const string qrjq1o = "qrjq1o";
        public const string qrjq1p = "qrjq1p";
        public const string qrjq1q = "qrjq1q";
        public const string qrjq1r = "qrjq1r";
        public const string qrjq1s = "qrjq1s";
        public const string qrjq1t = "qrjq1t";
        public const string qrjq1u = "qrjq1u";
        public const string qrjq1v = "qrjq1v";
        public const string qrjq1w = "qrjq1w";
        public const string qrjq1x = "qrjq1x";
        public const string qrjq1y = "qrjq1y";
        public const string qrjq1z = "qrjq1z";
        public const string qrjq2a = "qrjq2a";
        public const string qrjq2b = "qrjq2b";
        public const string qrjq2c = "qrjq2c";
        public const string qrjq2d = "qrjq2d";
        public const string qrjq2e = "qrjq2e";
        public const string qrjq2f = "qrjq2f";
        public const string qrjq2g = "qrjq2g";
        public const string qrjq2h = "qrjq2h";
        public const string qrjq2i = "qrjq2i";
        public const string qrjq2j = "qrjq2j";
        public const string qrjq2k = "qrjq2k";
        public const string qrjq2l = "qrjq2l";
        public const string qrjq2m = "qrjq2m";
        public const string qrjq2n = "qrjq2n";
        public const string qrjq2o = "qrjq2o";
        public const string qrjq2p = "qrjq2p";
        public const string qrjq2q = "qrjq2q";
        public const string qrjq2r = "qrjq2r";
        public const string qrjq2s = "qrjq2s";
        public const string qrjq2t = "qrjq2t";
        public const string qrjq2u = "qrjq2u";
        public const string qrjq2v = "qrjq2v";
        public const string qrjq2w = "qrjq2w";
        public const string qrjq2x = "qrjq2x";
        public const string qrjq2y = "qrjq2y";
        public const string qrjq2z = "qrjq2z";
        public const string qrjq3a = "qrjq3a";
        public const string qrjq3b = "qrjq3b";
        public const string qrjq3c = "qrjq3c";
        public const string qrjq3d = "qrjq3d";
        public const string qrjq3e = "qrjq3e";
        public const string qrjq3f = "qrjq3f";
        public const string qrjq3g = "qrjq3g";
        public const string qrjq3h = "qrjq3h";
        public const string qrjq3i = "qrjq3i";
        public const string qrjq3j = "qrjq3j";
        public const string qrjq3k = "qrjq3k";
        public const string qrjq3l = "qrjq3l";
        public const string qrjq3m = "qrjq3m";
        public const string qrjq10 = "qrjq10";
        public const string qrjq11 = "qrjq11";
        public const string qrjq12 = "qrjq12";
        public const string qrjq13 = "qrjq13";
        public const string qrjq14 = "qrjq14";
        public const string qrjq15 = "qrjq15";
        public const string qrjq16 = "qrjq16";
        public const string qrjq17 = "qrjq17";
        public const string qrjq18 = "qrjq18";
        public const string qrjq19 = "qrjq19";
        public const string qrjq20 = "qrjq20";
        public const string qrjq21 = "qrjq21";
        public const string qrjq22 = "qrjq22";
        public const string qrjq23 = "qrjq23";
        public const string qrjq24 = "qrjq24";
        public const string qrjq25 = "qrjq25";
        public const string qrjq26 = "qrjq26";
        public const string qrjq27 = "qrjq27";
        public const string qrjq28 = "qrjq28";
        public const string qrjq29 = "qrjq29";
        public const string qrjq30 = "qrjq30";
        public const string qrjq31 = "qrjq31";
        public const string qrjq32 = "qrjq32";
        public const string qrjq33 = "qrjq33";
        public const string qrjq34 = "qrjq34";
        public const string qrjq35 = "qrjq35";
        public const string qrjq36 = "qrjq36";
        public const string qrjq37 = "qrjq37";
        public const string qrjq38 = "qrjq38";
        public const string qrjq39 = "qrjq39";
    }
}
