// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtobufMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtobufMessage.proto</summary>
public static partial class ProtobufMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtobufMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtobufMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVQcm90b2J1Zk1lc3NhZ2UucHJvdG8aE01lc3NhZ2VIZWFkZXIucHJvdG8a",
          "FlRoVENIUHJvamVjdERhdGEucHJvdG8aFVRoU1VQcm9qZWN0RGF0YS5wcm90",
          "byKBAQoPUHJvdG9idWZNZXNzYWdlEh4KBmhlYWRlchgBIAEoCzIOLk1lc3Nh",
          "Z2VIZWFkZXISJwoMY2FkX3Byb2plY3RzGAIgAygLMhEuVGhUQ0hQcm9qZWN0",
          "RGF0YRIlCgtzdV9wcm9qZWN0cxgDIAMoCzIQLlRoU1VQcm9qZWN0RGF0YWIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MessageHeaderReflection.Descriptor, global::ThTCHProjectDataReflection.Descriptor, global::ThSUProjectDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMessage), global::ProtobufMessage.Parser, new[]{ "Header", "CadProjects", "SuProjects" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ProtobufMessage : pb::IMessage<ProtobufMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtobufMessage> _parser = new pb::MessageParser<ProtobufMessage>(() => new ProtobufMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtobufMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtobufMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtobufMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtobufMessage(ProtobufMessage other) : this() {
    header_ = other.header_ != null ? other.header_.Clone() : null;
    cadProjects_ = other.cadProjects_.Clone();
    suProjects_ = other.suProjects_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtobufMessage Clone() {
    return new ProtobufMessage(this);
  }

  /// <summary>Field number for the "header" field.</summary>
  public const int HeaderFieldNumber = 1;
  private global::MessageHeader header_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MessageHeader Header {
    get { return header_; }
    set {
      header_ = value;
    }
  }

  /// <summary>Field number for the "cad_projects" field.</summary>
  public const int CadProjectsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThTCHProjectData> _repeated_cadProjects_codec
      = pb::FieldCodec.ForMessage(18, global::ThTCHProjectData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHProjectData> cadProjects_ = new pbc::RepeatedField<global::ThTCHProjectData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHProjectData> CadProjects {
    get { return cadProjects_; }
  }

  /// <summary>Field number for the "su_projects" field.</summary>
  public const int SuProjectsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::ThSUProjectData> _repeated_suProjects_codec
      = pb::FieldCodec.ForMessage(26, global::ThSUProjectData.Parser);
  private readonly pbc::RepeatedField<global::ThSUProjectData> suProjects_ = new pbc::RepeatedField<global::ThSUProjectData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThSUProjectData> SuProjects {
    get { return suProjects_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtobufMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtobufMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Header, other.Header)) return false;
    if(!cadProjects_.Equals(other.cadProjects_)) return false;
    if(!suProjects_.Equals(other.suProjects_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (header_ != null) hash ^= Header.GetHashCode();
    hash ^= cadProjects_.GetHashCode();
    hash ^= suProjects_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (header_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Header);
    }
    cadProjects_.WriteTo(output, _repeated_cadProjects_codec);
    suProjects_.WriteTo(output, _repeated_suProjects_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (header_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Header);
    }
    cadProjects_.WriteTo(ref output, _repeated_cadProjects_codec);
    suProjects_.WriteTo(ref output, _repeated_suProjects_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (header_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
    }
    size += cadProjects_.CalculateSize(_repeated_cadProjects_codec);
    size += suProjects_.CalculateSize(_repeated_suProjects_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtobufMessage other) {
    if (other == null) {
      return;
    }
    if (other.header_ != null) {
      if (header_ == null) {
        Header = new global::MessageHeader();
      }
      Header.MergeFrom(other.Header);
    }
    cadProjects_.Add(other.cadProjects_);
    suProjects_.Add(other.suProjects_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (header_ == null) {
            Header = new global::MessageHeader();
          }
          input.ReadMessage(Header);
          break;
        }
        case 18: {
          cadProjects_.AddEntriesFrom(input, _repeated_cadProjects_codec);
          break;
        }
        case 26: {
          suProjects_.AddEntriesFrom(input, _repeated_suProjects_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (header_ == null) {
            Header = new global::MessageHeader();
          }
          input.ReadMessage(Header);
          break;
        }
        case 18: {
          cadProjects_.AddEntriesFrom(ref input, _repeated_cadProjects_codec);
          break;
        }
        case 26: {
          suProjects_.AddEntriesFrom(ref input, _repeated_suProjects_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
