// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThGridLineSyetemData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThGridLineSyetemData.proto</summary>
public static partial class ThGridLineSyetemDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThGridLineSyetemData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThGridLineSyetemDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpUaEdyaWRMaW5lU3lldGVtRGF0YS5wcm90bxoTVGhUQ0hSb290RGF0YS5w",
          "cm90bxoTVGhUQ0hHZW9tZXRyeS5wcm90bxocVGhDaXJjbGVMYWJsZUdyb3Vw",
          "RGF0YS5wcm90bxoaVGhEaW1lbnNpb25Hcm91cERhdGEucHJvdG8ivwEKFFRo",
          "R3JpZExpbmVTeWV0ZW1EYXRhEhwKBHJvb3QYASABKAsyDi5UaFRDSFJvb3RE",
          "YXRhEiIKCmdyaWRfbGluZXMYAiADKAsyDi5UaFRDSFBvbHlsaW5lEjQKE2Np",
          "cmNsZV9sYWJsZV9ncm91cHMYAyADKAsyFy5UaENpcmNsZUxhYmxlR3JvdXBE",
          "YXRhEi8KEGRpbWVuc2lvbl9ncm91cHMYBCADKAsyFS5UaERpbWVuc2lvbkdy",
          "b3VwRGF0YWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThTCHRootDataReflection.Descriptor, global::ThTCHGeometryReflection.Descriptor, global::ThCircleLableGroupDataReflection.Descriptor, global::ThDimensionGroupDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThGridLineSyetemData), global::ThGridLineSyetemData.Parser, new[]{ "Root", "GridLines", "CircleLableGroups", "DimensionGroups" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThGridLineSyetemData : pb::IMessage<ThGridLineSyetemData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThGridLineSyetemData> _parser = new pb::MessageParser<ThGridLineSyetemData>(() => new ThGridLineSyetemData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThGridLineSyetemData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThGridLineSyetemDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThGridLineSyetemData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThGridLineSyetemData(ThGridLineSyetemData other) : this() {
    root_ = other.root_ != null ? other.root_.Clone() : null;
    gridLines_ = other.gridLines_.Clone();
    circleLableGroups_ = other.circleLableGroups_.Clone();
    dimensionGroups_ = other.dimensionGroups_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThGridLineSyetemData Clone() {
    return new ThGridLineSyetemData(this);
  }

  /// <summary>Field number for the "root" field.</summary>
  public const int RootFieldNumber = 1;
  private global::ThTCHRootData root_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHRootData Root {
    get { return root_; }
    set {
      root_ = value;
    }
  }

  /// <summary>Field number for the "grid_lines" field.</summary>
  public const int GridLinesFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThTCHPolyline> _repeated_gridLines_codec
      = pb::FieldCodec.ForMessage(18, global::ThTCHPolyline.Parser);
  private readonly pbc::RepeatedField<global::ThTCHPolyline> gridLines_ = new pbc::RepeatedField<global::ThTCHPolyline>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHPolyline> GridLines {
    get { return gridLines_; }
  }

  /// <summary>Field number for the "circle_lable_groups" field.</summary>
  public const int CircleLableGroupsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::ThCircleLableGroupData> _repeated_circleLableGroups_codec
      = pb::FieldCodec.ForMessage(26, global::ThCircleLableGroupData.Parser);
  private readonly pbc::RepeatedField<global::ThCircleLableGroupData> circleLableGroups_ = new pbc::RepeatedField<global::ThCircleLableGroupData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThCircleLableGroupData> CircleLableGroups {
    get { return circleLableGroups_; }
  }

  /// <summary>Field number for the "dimension_groups" field.</summary>
  public const int DimensionGroupsFieldNumber = 4;
  private static readonly pb::FieldCodec<global::ThDimensionGroupData> _repeated_dimensionGroups_codec
      = pb::FieldCodec.ForMessage(34, global::ThDimensionGroupData.Parser);
  private readonly pbc::RepeatedField<global::ThDimensionGroupData> dimensionGroups_ = new pbc::RepeatedField<global::ThDimensionGroupData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThDimensionGroupData> DimensionGroups {
    get { return dimensionGroups_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThGridLineSyetemData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThGridLineSyetemData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Root, other.Root)) return false;
    if(!gridLines_.Equals(other.gridLines_)) return false;
    if(!circleLableGroups_.Equals(other.circleLableGroups_)) return false;
    if(!dimensionGroups_.Equals(other.dimensionGroups_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (root_ != null) hash ^= Root.GetHashCode();
    hash ^= gridLines_.GetHashCode();
    hash ^= circleLableGroups_.GetHashCode();
    hash ^= dimensionGroups_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    gridLines_.WriteTo(output, _repeated_gridLines_codec);
    circleLableGroups_.WriteTo(output, _repeated_circleLableGroups_codec);
    dimensionGroups_.WriteTo(output, _repeated_dimensionGroups_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    gridLines_.WriteTo(ref output, _repeated_gridLines_codec);
    circleLableGroups_.WriteTo(ref output, _repeated_circleLableGroups_codec);
    dimensionGroups_.WriteTo(ref output, _repeated_dimensionGroups_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (root_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
    }
    size += gridLines_.CalculateSize(_repeated_gridLines_codec);
    size += circleLableGroups_.CalculateSize(_repeated_circleLableGroups_codec);
    size += dimensionGroups_.CalculateSize(_repeated_dimensionGroups_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThGridLineSyetemData other) {
    if (other == null) {
      return;
    }
    if (other.root_ != null) {
      if (root_ == null) {
        Root = new global::ThTCHRootData();
      }
      Root.MergeFrom(other.Root);
    }
    gridLines_.Add(other.gridLines_);
    circleLableGroups_.Add(other.circleLableGroups_);
    dimensionGroups_.Add(other.dimensionGroups_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          gridLines_.AddEntriesFrom(input, _repeated_gridLines_codec);
          break;
        }
        case 26: {
          circleLableGroups_.AddEntriesFrom(input, _repeated_circleLableGroups_codec);
          break;
        }
        case 34: {
          dimensionGroups_.AddEntriesFrom(input, _repeated_dimensionGroups_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          gridLines_.AddEntriesFrom(ref input, _repeated_gridLines_codec);
          break;
        }
        case 26: {
          circleLableGroups_.AddEntriesFrom(ref input, _repeated_circleLableGroups_codec);
          break;
        }
        case 34: {
          dimensionGroups_.AddEntriesFrom(ref input, _repeated_dimensionGroups_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
