// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThSUFaceData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThSUFaceData.proto</summary>
public static partial class ThSUFaceDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThSUFaceData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThSUFaceDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJUaFNVRmFjZURhdGEucHJvdG8aElRoU1VMb29wRGF0YS5wcm90byJVCgxU",
          "aFNVRmFjZURhdGESIQoKb3V0ZXJfbG9vcBgBIAEoCzINLlRoU1VMb29wRGF0",
          "YRIiCgtpbm5lcl9sb29wcxgCIAMoCzINLlRoU1VMb29wRGF0YWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThSULoopDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThSUFaceData), global::ThSUFaceData.Parser, new[]{ "OuterLoop", "InnerLoops" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThSUFaceData : pb::IMessage<ThSUFaceData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThSUFaceData> _parser = new pb::MessageParser<ThSUFaceData>(() => new ThSUFaceData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThSUFaceData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThSUFaceDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFaceData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFaceData(ThSUFaceData other) : this() {
    outerLoop_ = other.outerLoop_ != null ? other.outerLoop_.Clone() : null;
    innerLoops_ = other.innerLoops_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFaceData Clone() {
    return new ThSUFaceData(this);
  }

  /// <summary>Field number for the "outer_loop" field.</summary>
  public const int OuterLoopFieldNumber = 1;
  private global::ThSULoopData outerLoop_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThSULoopData OuterLoop {
    get { return outerLoop_; }
    set {
      outerLoop_ = value;
    }
  }

  /// <summary>Field number for the "inner_loops" field.</summary>
  public const int InnerLoopsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThSULoopData> _repeated_innerLoops_codec
      = pb::FieldCodec.ForMessage(18, global::ThSULoopData.Parser);
  private readonly pbc::RepeatedField<global::ThSULoopData> innerLoops_ = new pbc::RepeatedField<global::ThSULoopData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThSULoopData> InnerLoops {
    get { return innerLoops_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThSUFaceData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThSUFaceData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(OuterLoop, other.OuterLoop)) return false;
    if(!innerLoops_.Equals(other.innerLoops_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (outerLoop_ != null) hash ^= OuterLoop.GetHashCode();
    hash ^= innerLoops_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (outerLoop_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(OuterLoop);
    }
    innerLoops_.WriteTo(output, _repeated_innerLoops_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (outerLoop_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(OuterLoop);
    }
    innerLoops_.WriteTo(ref output, _repeated_innerLoops_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (outerLoop_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(OuterLoop);
    }
    size += innerLoops_.CalculateSize(_repeated_innerLoops_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThSUFaceData other) {
    if (other == null) {
      return;
    }
    if (other.outerLoop_ != null) {
      if (outerLoop_ == null) {
        OuterLoop = new global::ThSULoopData();
      }
      OuterLoop.MergeFrom(other.OuterLoop);
    }
    innerLoops_.Add(other.innerLoops_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (outerLoop_ == null) {
            OuterLoop = new global::ThSULoopData();
          }
          input.ReadMessage(OuterLoop);
          break;
        }
        case 18: {
          innerLoops_.AddEntriesFrom(input, _repeated_innerLoops_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (outerLoop_ == null) {
            OuterLoop = new global::ThSULoopData();
          }
          input.ReadMessage(OuterLoop);
          break;
        }
        case 18: {
          innerLoops_.AddEntriesFrom(ref input, _repeated_innerLoops_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
