// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThSUComponentData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThSUComponentData.proto</summary>
public static partial class ThSUComponentDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThSUComponentData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThSUComponentDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdUaFNVQ29tcG9uZW50RGF0YS5wcm90bxoTVGhUQ0hHZW9tZXRyeS5wcm90",
          "bxocVGhTVUNvbXBEZWZpbml0aW9uRGF0YS5wcm90byJpChFUaFNVQ29tcG9u",
          "ZW50RGF0YRIrCgpkZWZpbml0aW9uGAEgASgLMhcuVGhTVUNvbXBEZWZpbml0",
          "aW9uRGF0YRInCg90cmFuc2Zvcm1hdGlvbnMYAiABKAsyDi5UaFRDSE1hdHJp",
          "eDNkYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThTCHGeometryReflection.Descriptor, global::ThSUCompDefinitionDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThSUComponentData), global::ThSUComponentData.Parser, new[]{ "Definition", "Transformations" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThSUComponentData : pb::IMessage<ThSUComponentData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThSUComponentData> _parser = new pb::MessageParser<ThSUComponentData>(() => new ThSUComponentData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThSUComponentData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThSUComponentDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUComponentData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUComponentData(ThSUComponentData other) : this() {
    definition_ = other.definition_ != null ? other.definition_.Clone() : null;
    transformations_ = other.transformations_ != null ? other.transformations_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUComponentData Clone() {
    return new ThSUComponentData(this);
  }

  /// <summary>Field number for the "definition" field.</summary>
  public const int DefinitionFieldNumber = 1;
  private global::ThSUCompDefinitionData definition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThSUCompDefinitionData Definition {
    get { return definition_; }
    set {
      definition_ = value;
    }
  }

  /// <summary>Field number for the "transformations" field.</summary>
  public const int TransformationsFieldNumber = 2;
  private global::ThTCHMatrix3d transformations_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHMatrix3d Transformations {
    get { return transformations_; }
    set {
      transformations_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThSUComponentData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThSUComponentData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Definition, other.Definition)) return false;
    if (!object.Equals(Transformations, other.Transformations)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (definition_ != null) hash ^= Definition.GetHashCode();
    if (transformations_ != null) hash ^= Transformations.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (definition_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Definition);
    }
    if (transformations_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Transformations);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (definition_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Definition);
    }
    if (transformations_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Transformations);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (definition_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Definition);
    }
    if (transformations_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transformations);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThSUComponentData other) {
    if (other == null) {
      return;
    }
    if (other.definition_ != null) {
      if (definition_ == null) {
        Definition = new global::ThSUCompDefinitionData();
      }
      Definition.MergeFrom(other.Definition);
    }
    if (other.transformations_ != null) {
      if (transformations_ == null) {
        Transformations = new global::ThTCHMatrix3d();
      }
      Transformations.MergeFrom(other.Transformations);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (definition_ == null) {
            Definition = new global::ThSUCompDefinitionData();
          }
          input.ReadMessage(Definition);
          break;
        }
        case 18: {
          if (transformations_ == null) {
            Transformations = new global::ThTCHMatrix3d();
          }
          input.ReadMessage(Transformations);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (definition_ == null) {
            Definition = new global::ThSUCompDefinitionData();
          }
          input.ReadMessage(Definition);
          break;
        }
        case 18: {
          if (transformations_ == null) {
            Transformations = new global::ThTCHMatrix3d();
          }
          input.ReadMessage(Transformations);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
