// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThSUProjectData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThSUProjectData.proto</summary>
public static partial class ThSUProjectDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThSUProjectData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThSUProjectDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVUaFNVUHJvamVjdERhdGEucHJvdG8aE1RoVENIUm9vdERhdGEucHJvdG8a",
          "HFRoU1VDb21wRGVmaW5pdGlvbkRhdGEucHJvdG8aFlRoU1VCdWlsZGluZ0Rh",
          "dGEucHJvdG8i8AEKD1RoU1VQcm9qZWN0RGF0YRIcCgRyb290GAEgASgLMg4u",
          "VGhUQ0hSb290RGF0YRIsCgtkZWZpbml0aW9ucxgCIAMoCzIXLlRoU1VDb21w",
          "RGVmaW5pdGlvbkRhdGESIwoIYnVpbGRpbmcYAyABKAsyES5UaFNVQnVpbGRp",
          "bmdEYXRhEhQKDGlzX2ZhY2VfbWVzaBgEIAEoCBIUCgxwcm9qZWN0X3BhdGgY",
          "BSABKAkSEgoKcHJvamVjdF9pZBgGIAEoCRIWCg5wcm9qZWN0X3N1Yl9pZBgH",
          "IAEoCRIUCgxiaW5kaW5nX25hbWUYCCABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThTCHRootDataReflection.Descriptor, global::ThSUCompDefinitionDataReflection.Descriptor, global::ThSUBuildingDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThSUProjectData), global::ThSUProjectData.Parser, new[]{ "Root", "Definitions", "Building", "IsFaceMesh", "ProjectPath", "ProjectId", "ProjectSubId", "BindingName" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThSUProjectData : pb::IMessage<ThSUProjectData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThSUProjectData> _parser = new pb::MessageParser<ThSUProjectData>(() => new ThSUProjectData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThSUProjectData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThSUProjectDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUProjectData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUProjectData(ThSUProjectData other) : this() {
    root_ = other.root_ != null ? other.root_.Clone() : null;
    definitions_ = other.definitions_.Clone();
    building_ = other.building_ != null ? other.building_.Clone() : null;
    isFaceMesh_ = other.isFaceMesh_;
    projectPath_ = other.projectPath_;
    projectId_ = other.projectId_;
    projectSubId_ = other.projectSubId_;
    bindingName_ = other.bindingName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUProjectData Clone() {
    return new ThSUProjectData(this);
  }

  /// <summary>Field number for the "root" field.</summary>
  public const int RootFieldNumber = 1;
  private global::ThTCHRootData root_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHRootData Root {
    get { return root_; }
    set {
      root_ = value;
    }
  }

  /// <summary>Field number for the "definitions" field.</summary>
  public const int DefinitionsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThSUCompDefinitionData> _repeated_definitions_codec
      = pb::FieldCodec.ForMessage(18, global::ThSUCompDefinitionData.Parser);
  private readonly pbc::RepeatedField<global::ThSUCompDefinitionData> definitions_ = new pbc::RepeatedField<global::ThSUCompDefinitionData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThSUCompDefinitionData> Definitions {
    get { return definitions_; }
  }

  /// <summary>Field number for the "building" field.</summary>
  public const int BuildingFieldNumber = 3;
  private global::ThSUBuildingData building_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThSUBuildingData Building {
    get { return building_; }
    set {
      building_ = value;
    }
  }

  /// <summary>Field number for the "is_face_mesh" field.</summary>
  public const int IsFaceMeshFieldNumber = 4;
  private bool isFaceMesh_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsFaceMesh {
    get { return isFaceMesh_; }
    set {
      isFaceMesh_ = value;
    }
  }

  /// <summary>Field number for the "project_path" field.</summary>
  public const int ProjectPathFieldNumber = 5;
  private string projectPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectPath {
    get { return projectPath_; }
    set {
      projectPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "project_id" field.</summary>
  public const int ProjectIdFieldNumber = 6;
  private string projectId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectId {
    get { return projectId_; }
    set {
      projectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "project_sub_id" field.</summary>
  public const int ProjectSubIdFieldNumber = 7;
  private string projectSubId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectSubId {
    get { return projectSubId_; }
    set {
      projectSubId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "binding_name" field.</summary>
  public const int BindingNameFieldNumber = 8;
  private string bindingName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BindingName {
    get { return bindingName_; }
    set {
      bindingName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThSUProjectData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThSUProjectData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Root, other.Root)) return false;
    if(!definitions_.Equals(other.definitions_)) return false;
    if (!object.Equals(Building, other.Building)) return false;
    if (IsFaceMesh != other.IsFaceMesh) return false;
    if (ProjectPath != other.ProjectPath) return false;
    if (ProjectId != other.ProjectId) return false;
    if (ProjectSubId != other.ProjectSubId) return false;
    if (BindingName != other.BindingName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (root_ != null) hash ^= Root.GetHashCode();
    hash ^= definitions_.GetHashCode();
    if (building_ != null) hash ^= Building.GetHashCode();
    if (IsFaceMesh != false) hash ^= IsFaceMesh.GetHashCode();
    if (ProjectPath.Length != 0) hash ^= ProjectPath.GetHashCode();
    if (ProjectId.Length != 0) hash ^= ProjectId.GetHashCode();
    if (ProjectSubId.Length != 0) hash ^= ProjectSubId.GetHashCode();
    if (BindingName.Length != 0) hash ^= BindingName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    definitions_.WriteTo(output, _repeated_definitions_codec);
    if (building_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Building);
    }
    if (IsFaceMesh != false) {
      output.WriteRawTag(32);
      output.WriteBool(IsFaceMesh);
    }
    if (ProjectPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ProjectPath);
    }
    if (ProjectId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(ProjectSubId);
    }
    if (BindingName.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(BindingName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    definitions_.WriteTo(ref output, _repeated_definitions_codec);
    if (building_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Building);
    }
    if (IsFaceMesh != false) {
      output.WriteRawTag(32);
      output.WriteBool(IsFaceMesh);
    }
    if (ProjectPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ProjectPath);
    }
    if (ProjectId.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(ProjectSubId);
    }
    if (BindingName.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(BindingName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (root_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
    }
    size += definitions_.CalculateSize(_repeated_definitions_codec);
    if (building_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Building);
    }
    if (IsFaceMesh != false) {
      size += 1 + 1;
    }
    if (ProjectPath.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectPath);
    }
    if (ProjectId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectSubId);
    }
    if (BindingName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BindingName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThSUProjectData other) {
    if (other == null) {
      return;
    }
    if (other.root_ != null) {
      if (root_ == null) {
        Root = new global::ThTCHRootData();
      }
      Root.MergeFrom(other.Root);
    }
    definitions_.Add(other.definitions_);
    if (other.building_ != null) {
      if (building_ == null) {
        Building = new global::ThSUBuildingData();
      }
      Building.MergeFrom(other.Building);
    }
    if (other.IsFaceMesh != false) {
      IsFaceMesh = other.IsFaceMesh;
    }
    if (other.ProjectPath.Length != 0) {
      ProjectPath = other.ProjectPath;
    }
    if (other.ProjectId.Length != 0) {
      ProjectId = other.ProjectId;
    }
    if (other.ProjectSubId.Length != 0) {
      ProjectSubId = other.ProjectSubId;
    }
    if (other.BindingName.Length != 0) {
      BindingName = other.BindingName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          definitions_.AddEntriesFrom(input, _repeated_definitions_codec);
          break;
        }
        case 26: {
          if (building_ == null) {
            Building = new global::ThSUBuildingData();
          }
          input.ReadMessage(Building);
          break;
        }
        case 32: {
          IsFaceMesh = input.ReadBool();
          break;
        }
        case 42: {
          ProjectPath = input.ReadString();
          break;
        }
        case 50: {
          ProjectId = input.ReadString();
          break;
        }
        case 58: {
          ProjectSubId = input.ReadString();
          break;
        }
        case 66: {
          BindingName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          definitions_.AddEntriesFrom(ref input, _repeated_definitions_codec);
          break;
        }
        case 26: {
          if (building_ == null) {
            Building = new global::ThSUBuildingData();
          }
          input.ReadMessage(Building);
          break;
        }
        case 32: {
          IsFaceMesh = input.ReadBool();
          break;
        }
        case 42: {
          ProjectPath = input.ReadString();
          break;
        }
        case 50: {
          ProjectId = input.ReadString();
          break;
        }
        case 58: {
          ProjectSubId = input.ReadString();
          break;
        }
        case 66: {
          BindingName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
