// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThSUFollowSlopeRooofData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThSUFollowSlopeRooofData.proto</summary>
public static partial class ThSUFollowSlopeRooofDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThSUFollowSlopeRooofData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThSUFollowSlopeRooofDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch5UaFNVRm9sbG93U2xvcGVSb29vZkRhdGEucHJvdG8aHFRoU1VDb21wRGVm",
          "aW5pdGlvbkRhdGEucHJvdG8aIFRoU1VGb2xsb3dTbG9wZUVsZW1lbnREYXRh",
          "LnByb3RvIokBChhUaFNVRm9sbG93U2xvcGVSb29vZkRhdGESEAoIZ2xvYmFs",
          "SWQYASABKAkSLQoIZWxlbWVudHMYAiADKAsyGy5UaFNVRm9sbG93U2xvcGVF",
          "bGVtZW50RGF0YRIsCgtkZWZpbml0aW9ucxgDIAMoCzIXLlRoU1VDb21wRGVm",
          "aW5pdGlvbkRhdGFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThSUCompDefinitionDataReflection.Descriptor, global::ThSUFollowSlopeElementDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThSUFollowSlopeRooofData), global::ThSUFollowSlopeRooofData.Parser, new[]{ "GlobalId", "Elements", "Definitions" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThSUFollowSlopeRooofData : pb::IMessage<ThSUFollowSlopeRooofData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThSUFollowSlopeRooofData> _parser = new pb::MessageParser<ThSUFollowSlopeRooofData>(() => new ThSUFollowSlopeRooofData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThSUFollowSlopeRooofData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThSUFollowSlopeRooofDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFollowSlopeRooofData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFollowSlopeRooofData(ThSUFollowSlopeRooofData other) : this() {
    globalId_ = other.globalId_;
    elements_ = other.elements_.Clone();
    definitions_ = other.definitions_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThSUFollowSlopeRooofData Clone() {
    return new ThSUFollowSlopeRooofData(this);
  }

  /// <summary>Field number for the "globalId" field.</summary>
  public const int GlobalIdFieldNumber = 1;
  private string globalId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GlobalId {
    get { return globalId_; }
    set {
      globalId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "elements" field.</summary>
  public const int ElementsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThSUFollowSlopeElementData> _repeated_elements_codec
      = pb::FieldCodec.ForMessage(18, global::ThSUFollowSlopeElementData.Parser);
  private readonly pbc::RepeatedField<global::ThSUFollowSlopeElementData> elements_ = new pbc::RepeatedField<global::ThSUFollowSlopeElementData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThSUFollowSlopeElementData> Elements {
    get { return elements_; }
  }

  /// <summary>Field number for the "definitions" field.</summary>
  public const int DefinitionsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::ThSUCompDefinitionData> _repeated_definitions_codec
      = pb::FieldCodec.ForMessage(26, global::ThSUCompDefinitionData.Parser);
  private readonly pbc::RepeatedField<global::ThSUCompDefinitionData> definitions_ = new pbc::RepeatedField<global::ThSUCompDefinitionData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThSUCompDefinitionData> Definitions {
    get { return definitions_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThSUFollowSlopeRooofData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThSUFollowSlopeRooofData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (GlobalId != other.GlobalId) return false;
    if(!elements_.Equals(other.elements_)) return false;
    if(!definitions_.Equals(other.definitions_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (GlobalId.Length != 0) hash ^= GlobalId.GetHashCode();
    hash ^= elements_.GetHashCode();
    hash ^= definitions_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (GlobalId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(GlobalId);
    }
    elements_.WriteTo(output, _repeated_elements_codec);
    definitions_.WriteTo(output, _repeated_definitions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (GlobalId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(GlobalId);
    }
    elements_.WriteTo(ref output, _repeated_elements_codec);
    definitions_.WriteTo(ref output, _repeated_definitions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (GlobalId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GlobalId);
    }
    size += elements_.CalculateSize(_repeated_elements_codec);
    size += definitions_.CalculateSize(_repeated_definitions_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThSUFollowSlopeRooofData other) {
    if (other == null) {
      return;
    }
    if (other.GlobalId.Length != 0) {
      GlobalId = other.GlobalId;
    }
    elements_.Add(other.elements_);
    definitions_.Add(other.definitions_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          GlobalId = input.ReadString();
          break;
        }
        case 18: {
          elements_.AddEntriesFrom(input, _repeated_elements_codec);
          break;
        }
        case 26: {
          definitions_.AddEntriesFrom(input, _repeated_definitions_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          GlobalId = input.ReadString();
          break;
        }
        case 18: {
          elements_.AddEntriesFrom(ref input, _repeated_elements_codec);
          break;
        }
        case 26: {
          definitions_.AddEntriesFrom(ref input, _repeated_definitions_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
