// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThTCHProjectData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThTCHProjectData.proto</summary>
public static partial class ThTCHProjectDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThTCHProjectData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThTCHProjectDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZUaFRDSFByb2plY3REYXRhLnByb3RvGhNUaFRDSFJvb3REYXRhLnByb3Rv",
          "GhNUaFRDSFNpdGVEYXRhLnByb3RvIqcBChBUaFRDSFByb2plY3REYXRhEhwK",
          "BHJvb3QYASABKAsyDi5UaFRDSFJvb3REYXRhEh0KBXNpdGVzGAIgAygLMg4u",
          "VGhUQ0hTaXRlRGF0YRISCgpwcm9qZWN0X2lkGAMgASgJEhYKDnByb2plY3Rf",
          "c3ViX2lkGAQgASgJEhQKDHByb2plY3RfcGF0aBgFIAEoCRIUCgxiaW5kaW5n",
          "X25hbWUYBiABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThTCHRootDataReflection.Descriptor, global::ThTCHSiteDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHProjectData), global::ThTCHProjectData.Parser, new[]{ "Root", "Sites", "ProjectId", "ProjectSubId", "ProjectPath", "BindingName" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThTCHProjectData : pb::IMessage<ThTCHProjectData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHProjectData> _parser = new pb::MessageParser<ThTCHProjectData>(() => new ThTCHProjectData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHProjectData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHProjectDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHProjectData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHProjectData(ThTCHProjectData other) : this() {
    root_ = other.root_ != null ? other.root_.Clone() : null;
    sites_ = other.sites_.Clone();
    projectId_ = other.projectId_;
    projectSubId_ = other.projectSubId_;
    projectPath_ = other.projectPath_;
    bindingName_ = other.bindingName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHProjectData Clone() {
    return new ThTCHProjectData(this);
  }

  /// <summary>Field number for the "root" field.</summary>
  public const int RootFieldNumber = 1;
  private global::ThTCHRootData root_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHRootData Root {
    get { return root_; }
    set {
      root_ = value;
    }
  }

  /// <summary>Field number for the "sites" field.</summary>
  public const int SitesFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThTCHSiteData> _repeated_sites_codec
      = pb::FieldCodec.ForMessage(18, global::ThTCHSiteData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHSiteData> sites_ = new pbc::RepeatedField<global::ThTCHSiteData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHSiteData> Sites {
    get { return sites_; }
  }

  /// <summary>Field number for the "project_id" field.</summary>
  public const int ProjectIdFieldNumber = 3;
  private string projectId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectId {
    get { return projectId_; }
    set {
      projectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "project_sub_id" field.</summary>
  public const int ProjectSubIdFieldNumber = 4;
  private string projectSubId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectSubId {
    get { return projectSubId_; }
    set {
      projectSubId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "project_path" field.</summary>
  public const int ProjectPathFieldNumber = 5;
  private string projectPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProjectPath {
    get { return projectPath_; }
    set {
      projectPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "binding_name" field.</summary>
  public const int BindingNameFieldNumber = 6;
  private string bindingName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BindingName {
    get { return bindingName_; }
    set {
      bindingName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHProjectData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHProjectData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Root, other.Root)) return false;
    if(!sites_.Equals(other.sites_)) return false;
    if (ProjectId != other.ProjectId) return false;
    if (ProjectSubId != other.ProjectSubId) return false;
    if (ProjectPath != other.ProjectPath) return false;
    if (BindingName != other.BindingName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (root_ != null) hash ^= Root.GetHashCode();
    hash ^= sites_.GetHashCode();
    if (ProjectId.Length != 0) hash ^= ProjectId.GetHashCode();
    if (ProjectSubId.Length != 0) hash ^= ProjectSubId.GetHashCode();
    if (ProjectPath.Length != 0) hash ^= ProjectPath.GetHashCode();
    if (BindingName.Length != 0) hash ^= BindingName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    sites_.WriteTo(output, _repeated_sites_codec);
    if (ProjectId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ProjectSubId);
    }
    if (ProjectPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ProjectPath);
    }
    if (BindingName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(BindingName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (root_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Root);
    }
    sites_.WriteTo(ref output, _repeated_sites_codec);
    if (ProjectId.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ProjectSubId);
    }
    if (ProjectPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ProjectPath);
    }
    if (BindingName.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(BindingName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (root_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
    }
    size += sites_.CalculateSize(_repeated_sites_codec);
    if (ProjectId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectId);
    }
    if (ProjectSubId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectSubId);
    }
    if (ProjectPath.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectPath);
    }
    if (BindingName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BindingName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHProjectData other) {
    if (other == null) {
      return;
    }
    if (other.root_ != null) {
      if (root_ == null) {
        Root = new global::ThTCHRootData();
      }
      Root.MergeFrom(other.Root);
    }
    sites_.Add(other.sites_);
    if (other.ProjectId.Length != 0) {
      ProjectId = other.ProjectId;
    }
    if (other.ProjectSubId.Length != 0) {
      ProjectSubId = other.ProjectSubId;
    }
    if (other.ProjectPath.Length != 0) {
      ProjectPath = other.ProjectPath;
    }
    if (other.BindingName.Length != 0) {
      BindingName = other.BindingName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          sites_.AddEntriesFrom(input, _repeated_sites_codec);
          break;
        }
        case 26: {
          ProjectId = input.ReadString();
          break;
        }
        case 34: {
          ProjectSubId = input.ReadString();
          break;
        }
        case 42: {
          ProjectPath = input.ReadString();
          break;
        }
        case 50: {
          BindingName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (root_ == null) {
            Root = new global::ThTCHRootData();
          }
          input.ReadMessage(Root);
          break;
        }
        case 18: {
          sites_.AddEntriesFrom(ref input, _repeated_sites_codec);
          break;
        }
        case 26: {
          ProjectId = input.ReadString();
          break;
        }
        case 34: {
          ProjectSubId = input.ReadString();
          break;
        }
        case 42: {
          ProjectPath = input.ReadString();
          break;
        }
        case 50: {
          BindingName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
