// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThTCHGeometry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThTCHGeometry.proto</summary>
public static partial class ThTCHGeometryReflection {

  #region Descriptor
  /// <summary>File descriptor for ThTCHGeometry.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThTCHGeometryReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNUaFRDSEdlb21ldHJ5LnByb3RvIi8KDFRoVENIUG9pbnQzZBIJCgF4GAEg",
          "ASgBEgkKAXkYAiABKAESCQoBehgDIAEoASIwCg1UaFRDSFZlY3RvcjNkEgkK",
          "AXgYASABKAESCQoBeRgCIAEoARIJCgF6GAMgASgBIo8CCg1UaFRDSE1hdHJp",
          "eDNkEg4KBmRhdGExMRgBIAEoARIOCgZkYXRhMTIYAiABKAESDgoGZGF0YTEz",
          "GAMgASgBEg4KBmRhdGExNBgEIAEoARIOCgZkYXRhMjEYBSABKAESDgoGZGF0",
          "YTIyGAYgASgBEg4KBmRhdGEyMxgHIAEoARIOCgZkYXRhMjQYCCABKAESDgoG",
          "ZGF0YTMxGAkgASgBEg4KBmRhdGEzMhgKIAEoARIOCgZkYXRhMzMYCyABKAES",
          "DgoGZGF0YTM0GAwgASgBEg4KBmRhdGE0MRgNIAEoARIOCgZkYXRhNDIYDiAB",
          "KAESDgoGZGF0YTQzGA8gASgBEg4KBmRhdGE0NBgQIAEoASIdCgxUaFRDSFNl",
          "Z21lbnQSDQoFaW5kZXgYASADKA0iTwoNVGhUQ0hQb2x5bGluZRIdCgZwb2lu",
          "dHMYASADKAsyDS5UaFRDSFBvaW50M2QSHwoIc2VnbWVudHMYAiADKAsyDS5U",
          "aFRDSFNlZ21lbnRiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHPoint3d), global::ThTCHPoint3d.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHVector3d), global::ThTCHVector3d.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHMatrix3d), global::ThTCHMatrix3d.Parser, new[]{ "Data11", "Data12", "Data13", "Data14", "Data21", "Data22", "Data23", "Data24", "Data31", "Data32", "Data33", "Data34", "Data41", "Data42", "Data43", "Data44" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHSegment), global::ThTCHSegment.Parser, new[]{ "Index" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHPolyline), global::ThTCHPolyline.Parser, new[]{ "Points", "Segments" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThTCHPoint3d : pb::IMessage<ThTCHPoint3d>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHPoint3d> _parser = new pb::MessageParser<ThTCHPoint3d>(() => new ThTCHPoint3d());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHPoint3d> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHGeometryReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPoint3d() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPoint3d(ThTCHPoint3d other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPoint3d Clone() {
    return new ThTCHPoint3d(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private double x_;
  /// <summary>
  /// X coordinate
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private double y_;
  /// <summary>
  /// Y coordinate
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private double z_;
  /// <summary>
  /// Z coordinate
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Z {
    get { return z_; }
    set {
      z_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHPoint3d);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHPoint3d other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Y, other.Y)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Z, other.Z)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(X);
    if (Y != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Y);
    if (Z != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Z);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(X);
    }
    if (Y != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Y);
    }
    if (Z != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(X);
    }
    if (Y != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Y);
    }
    if (Z != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0D) {
      size += 1 + 8;
    }
    if (Y != 0D) {
      size += 1 + 8;
    }
    if (Z != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHPoint3d other) {
    if (other == null) {
      return;
    }
    if (other.X != 0D) {
      X = other.X;
    }
    if (other.Y != 0D) {
      Y = other.Y;
    }
    if (other.Z != 0D) {
      Z = other.Z;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          X = input.ReadDouble();
          break;
        }
        case 17: {
          Y = input.ReadDouble();
          break;
        }
        case 25: {
          Z = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          X = input.ReadDouble();
          break;
        }
        case 17: {
          Y = input.ReadDouble();
          break;
        }
        case 25: {
          Z = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ThTCHVector3d : pb::IMessage<ThTCHVector3d>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHVector3d> _parser = new pb::MessageParser<ThTCHVector3d>(() => new ThTCHVector3d());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHVector3d> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHGeometryReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHVector3d() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHVector3d(ThTCHVector3d other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHVector3d Clone() {
    return new ThTCHVector3d(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private double x_;
  /// <summary>
  /// X
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private double y_;
  /// <summary>
  /// Y
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private double z_;
  /// <summary>
  /// Z
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Z {
    get { return z_; }
    set {
      z_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHVector3d);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHVector3d other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Y, other.Y)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Z, other.Z)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(X);
    if (Y != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Y);
    if (Z != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Z);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(X);
    }
    if (Y != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Y);
    }
    if (Z != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(X);
    }
    if (Y != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Y);
    }
    if (Z != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0D) {
      size += 1 + 8;
    }
    if (Y != 0D) {
      size += 1 + 8;
    }
    if (Z != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHVector3d other) {
    if (other == null) {
      return;
    }
    if (other.X != 0D) {
      X = other.X;
    }
    if (other.Y != 0D) {
      Y = other.Y;
    }
    if (other.Z != 0D) {
      Z = other.Z;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          X = input.ReadDouble();
          break;
        }
        case 17: {
          Y = input.ReadDouble();
          break;
        }
        case 25: {
          Z = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          X = input.ReadDouble();
          break;
        }
        case 17: {
          Y = input.ReadDouble();
          break;
        }
        case 25: {
          Z = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ThTCHMatrix3d : pb::IMessage<ThTCHMatrix3d>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHMatrix3d> _parser = new pb::MessageParser<ThTCHMatrix3d>(() => new ThTCHMatrix3d());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHMatrix3d> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHGeometryReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHMatrix3d() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHMatrix3d(ThTCHMatrix3d other) : this() {
    data11_ = other.data11_;
    data12_ = other.data12_;
    data13_ = other.data13_;
    data14_ = other.data14_;
    data21_ = other.data21_;
    data22_ = other.data22_;
    data23_ = other.data23_;
    data24_ = other.data24_;
    data31_ = other.data31_;
    data32_ = other.data32_;
    data33_ = other.data33_;
    data34_ = other.data34_;
    data41_ = other.data41_;
    data42_ = other.data42_;
    data43_ = other.data43_;
    data44_ = other.data44_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHMatrix3d Clone() {
    return new ThTCHMatrix3d(this);
  }

  /// <summary>Field number for the "data11" field.</summary>
  public const int Data11FieldNumber = 1;
  private double data11_;
  /// <summary>
  /// r0 c0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data11 {
    get { return data11_; }
    set {
      data11_ = value;
    }
  }

  /// <summary>Field number for the "data12" field.</summary>
  public const int Data12FieldNumber = 2;
  private double data12_;
  /// <summary>
  /// r0 c1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data12 {
    get { return data12_; }
    set {
      data12_ = value;
    }
  }

  /// <summary>Field number for the "data13" field.</summary>
  public const int Data13FieldNumber = 3;
  private double data13_;
  /// <summary>
  /// r0 c2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data13 {
    get { return data13_; }
    set {
      data13_ = value;
    }
  }

  /// <summary>Field number for the "data14" field.</summary>
  public const int Data14FieldNumber = 4;
  private double data14_;
  /// <summary>
  /// r0 c3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data14 {
    get { return data14_; }
    set {
      data14_ = value;
    }
  }

  /// <summary>Field number for the "data21" field.</summary>
  public const int Data21FieldNumber = 5;
  private double data21_;
  /// <summary>
  /// r1 c0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data21 {
    get { return data21_; }
    set {
      data21_ = value;
    }
  }

  /// <summary>Field number for the "data22" field.</summary>
  public const int Data22FieldNumber = 6;
  private double data22_;
  /// <summary>
  /// r1 c1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data22 {
    get { return data22_; }
    set {
      data22_ = value;
    }
  }

  /// <summary>Field number for the "data23" field.</summary>
  public const int Data23FieldNumber = 7;
  private double data23_;
  /// <summary>
  /// r1 c2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data23 {
    get { return data23_; }
    set {
      data23_ = value;
    }
  }

  /// <summary>Field number for the "data24" field.</summary>
  public const int Data24FieldNumber = 8;
  private double data24_;
  /// <summary>
  /// r1 c3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data24 {
    get { return data24_; }
    set {
      data24_ = value;
    }
  }

  /// <summary>Field number for the "data31" field.</summary>
  public const int Data31FieldNumber = 9;
  private double data31_;
  /// <summary>
  /// r2 c0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data31 {
    get { return data31_; }
    set {
      data31_ = value;
    }
  }

  /// <summary>Field number for the "data32" field.</summary>
  public const int Data32FieldNumber = 10;
  private double data32_;
  /// <summary>
  /// r2 c1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data32 {
    get { return data32_; }
    set {
      data32_ = value;
    }
  }

  /// <summary>Field number for the "data33" field.</summary>
  public const int Data33FieldNumber = 11;
  private double data33_;
  /// <summary>
  /// r2 c2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data33 {
    get { return data33_; }
    set {
      data33_ = value;
    }
  }

  /// <summary>Field number for the "data34" field.</summary>
  public const int Data34FieldNumber = 12;
  private double data34_;
  /// <summary>
  /// r2 c3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data34 {
    get { return data34_; }
    set {
      data34_ = value;
    }
  }

  /// <summary>Field number for the "data41" field.</summary>
  public const int Data41FieldNumber = 13;
  private double data41_;
  /// <summary>
  /// r3 c0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data41 {
    get { return data41_; }
    set {
      data41_ = value;
    }
  }

  /// <summary>Field number for the "data42" field.</summary>
  public const int Data42FieldNumber = 14;
  private double data42_;
  /// <summary>
  /// r3 c1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data42 {
    get { return data42_; }
    set {
      data42_ = value;
    }
  }

  /// <summary>Field number for the "data43" field.</summary>
  public const int Data43FieldNumber = 15;
  private double data43_;
  /// <summary>
  /// r3 c2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data43 {
    get { return data43_; }
    set {
      data43_ = value;
    }
  }

  /// <summary>Field number for the "data44" field.</summary>
  public const int Data44FieldNumber = 16;
  private double data44_;
  /// <summary>
  /// r3 c3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Data44 {
    get { return data44_; }
    set {
      data44_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHMatrix3d);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHMatrix3d other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data11, other.Data11)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data12, other.Data12)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data13, other.Data13)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data14, other.Data14)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data21, other.Data21)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data22, other.Data22)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data23, other.Data23)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data24, other.Data24)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data31, other.Data31)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data32, other.Data32)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data33, other.Data33)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data34, other.Data34)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data41, other.Data41)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data42, other.Data42)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data43, other.Data43)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Data44, other.Data44)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Data11 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data11);
    if (Data12 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data12);
    if (Data13 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data13);
    if (Data14 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data14);
    if (Data21 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data21);
    if (Data22 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data22);
    if (Data23 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data23);
    if (Data24 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data24);
    if (Data31 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data31);
    if (Data32 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data32);
    if (Data33 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data33);
    if (Data34 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data34);
    if (Data41 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data41);
    if (Data42 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data42);
    if (Data43 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data43);
    if (Data44 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Data44);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Data11 != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Data11);
    }
    if (Data12 != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Data12);
    }
    if (Data13 != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Data13);
    }
    if (Data14 != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Data14);
    }
    if (Data21 != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Data21);
    }
    if (Data22 != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Data22);
    }
    if (Data23 != 0D) {
      output.WriteRawTag(57);
      output.WriteDouble(Data23);
    }
    if (Data24 != 0D) {
      output.WriteRawTag(65);
      output.WriteDouble(Data24);
    }
    if (Data31 != 0D) {
      output.WriteRawTag(73);
      output.WriteDouble(Data31);
    }
    if (Data32 != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(Data32);
    }
    if (Data33 != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(Data33);
    }
    if (Data34 != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(Data34);
    }
    if (Data41 != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(Data41);
    }
    if (Data42 != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(Data42);
    }
    if (Data43 != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(Data43);
    }
    if (Data44 != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(Data44);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Data11 != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Data11);
    }
    if (Data12 != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Data12);
    }
    if (Data13 != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Data13);
    }
    if (Data14 != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Data14);
    }
    if (Data21 != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Data21);
    }
    if (Data22 != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Data22);
    }
    if (Data23 != 0D) {
      output.WriteRawTag(57);
      output.WriteDouble(Data23);
    }
    if (Data24 != 0D) {
      output.WriteRawTag(65);
      output.WriteDouble(Data24);
    }
    if (Data31 != 0D) {
      output.WriteRawTag(73);
      output.WriteDouble(Data31);
    }
    if (Data32 != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(Data32);
    }
    if (Data33 != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(Data33);
    }
    if (Data34 != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(Data34);
    }
    if (Data41 != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(Data41);
    }
    if (Data42 != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(Data42);
    }
    if (Data43 != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(Data43);
    }
    if (Data44 != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(Data44);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Data11 != 0D) {
      size += 1 + 8;
    }
    if (Data12 != 0D) {
      size += 1 + 8;
    }
    if (Data13 != 0D) {
      size += 1 + 8;
    }
    if (Data14 != 0D) {
      size += 1 + 8;
    }
    if (Data21 != 0D) {
      size += 1 + 8;
    }
    if (Data22 != 0D) {
      size += 1 + 8;
    }
    if (Data23 != 0D) {
      size += 1 + 8;
    }
    if (Data24 != 0D) {
      size += 1 + 8;
    }
    if (Data31 != 0D) {
      size += 1 + 8;
    }
    if (Data32 != 0D) {
      size += 1 + 8;
    }
    if (Data33 != 0D) {
      size += 1 + 8;
    }
    if (Data34 != 0D) {
      size += 1 + 8;
    }
    if (Data41 != 0D) {
      size += 1 + 8;
    }
    if (Data42 != 0D) {
      size += 1 + 8;
    }
    if (Data43 != 0D) {
      size += 1 + 8;
    }
    if (Data44 != 0D) {
      size += 2 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHMatrix3d other) {
    if (other == null) {
      return;
    }
    if (other.Data11 != 0D) {
      Data11 = other.Data11;
    }
    if (other.Data12 != 0D) {
      Data12 = other.Data12;
    }
    if (other.Data13 != 0D) {
      Data13 = other.Data13;
    }
    if (other.Data14 != 0D) {
      Data14 = other.Data14;
    }
    if (other.Data21 != 0D) {
      Data21 = other.Data21;
    }
    if (other.Data22 != 0D) {
      Data22 = other.Data22;
    }
    if (other.Data23 != 0D) {
      Data23 = other.Data23;
    }
    if (other.Data24 != 0D) {
      Data24 = other.Data24;
    }
    if (other.Data31 != 0D) {
      Data31 = other.Data31;
    }
    if (other.Data32 != 0D) {
      Data32 = other.Data32;
    }
    if (other.Data33 != 0D) {
      Data33 = other.Data33;
    }
    if (other.Data34 != 0D) {
      Data34 = other.Data34;
    }
    if (other.Data41 != 0D) {
      Data41 = other.Data41;
    }
    if (other.Data42 != 0D) {
      Data42 = other.Data42;
    }
    if (other.Data43 != 0D) {
      Data43 = other.Data43;
    }
    if (other.Data44 != 0D) {
      Data44 = other.Data44;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Data11 = input.ReadDouble();
          break;
        }
        case 17: {
          Data12 = input.ReadDouble();
          break;
        }
        case 25: {
          Data13 = input.ReadDouble();
          break;
        }
        case 33: {
          Data14 = input.ReadDouble();
          break;
        }
        case 41: {
          Data21 = input.ReadDouble();
          break;
        }
        case 49: {
          Data22 = input.ReadDouble();
          break;
        }
        case 57: {
          Data23 = input.ReadDouble();
          break;
        }
        case 65: {
          Data24 = input.ReadDouble();
          break;
        }
        case 73: {
          Data31 = input.ReadDouble();
          break;
        }
        case 81: {
          Data32 = input.ReadDouble();
          break;
        }
        case 89: {
          Data33 = input.ReadDouble();
          break;
        }
        case 97: {
          Data34 = input.ReadDouble();
          break;
        }
        case 105: {
          Data41 = input.ReadDouble();
          break;
        }
        case 113: {
          Data42 = input.ReadDouble();
          break;
        }
        case 121: {
          Data43 = input.ReadDouble();
          break;
        }
        case 129: {
          Data44 = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Data11 = input.ReadDouble();
          break;
        }
        case 17: {
          Data12 = input.ReadDouble();
          break;
        }
        case 25: {
          Data13 = input.ReadDouble();
          break;
        }
        case 33: {
          Data14 = input.ReadDouble();
          break;
        }
        case 41: {
          Data21 = input.ReadDouble();
          break;
        }
        case 49: {
          Data22 = input.ReadDouble();
          break;
        }
        case 57: {
          Data23 = input.ReadDouble();
          break;
        }
        case 65: {
          Data24 = input.ReadDouble();
          break;
        }
        case 73: {
          Data31 = input.ReadDouble();
          break;
        }
        case 81: {
          Data32 = input.ReadDouble();
          break;
        }
        case 89: {
          Data33 = input.ReadDouble();
          break;
        }
        case 97: {
          Data34 = input.ReadDouble();
          break;
        }
        case 105: {
          Data41 = input.ReadDouble();
          break;
        }
        case 113: {
          Data42 = input.ReadDouble();
          break;
        }
        case 121: {
          Data43 = input.ReadDouble();
          break;
        }
        case 129: {
          Data44 = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ThTCHSegment : pb::IMessage<ThTCHSegment>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHSegment> _parser = new pb::MessageParser<ThTCHSegment>(() => new ThTCHSegment());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHSegment> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHGeometryReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHSegment() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHSegment(ThTCHSegment other) : this() {
    index_ = other.index_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHSegment Clone() {
    return new ThTCHSegment(this);
  }

  /// <summary>Field number for the "index" field.</summary>
  public const int IndexFieldNumber = 1;
  private static readonly pb::FieldCodec<uint> _repeated_index_codec
      = pb::FieldCodec.ForUInt32(10);
  private readonly pbc::RepeatedField<uint> index_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> Index {
    get { return index_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHSegment);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHSegment other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!index_.Equals(other.index_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= index_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    index_.WriteTo(output, _repeated_index_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    index_.WriteTo(ref output, _repeated_index_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += index_.CalculateSize(_repeated_index_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHSegment other) {
    if (other == null) {
      return;
    }
    index_.Add(other.index_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          index_.AddEntriesFrom(input, _repeated_index_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          index_.AddEntriesFrom(ref input, _repeated_index_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ThTCHPolyline : pb::IMessage<ThTCHPolyline>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHPolyline> _parser = new pb::MessageParser<ThTCHPolyline>(() => new ThTCHPolyline());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHPolyline> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHGeometryReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPolyline() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPolyline(ThTCHPolyline other) : this() {
    points_ = other.points_.Clone();
    segments_ = other.segments_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHPolyline Clone() {
    return new ThTCHPolyline(this);
  }

  /// <summary>Field number for the "points" field.</summary>
  public const int PointsFieldNumber = 1;
  private static readonly pb::FieldCodec<global::ThTCHPoint3d> _repeated_points_codec
      = pb::FieldCodec.ForMessage(10, global::ThTCHPoint3d.Parser);
  private readonly pbc::RepeatedField<global::ThTCHPoint3d> points_ = new pbc::RepeatedField<global::ThTCHPoint3d>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHPoint3d> Points {
    get { return points_; }
  }

  /// <summary>Field number for the "segments" field.</summary>
  public const int SegmentsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ThTCHSegment> _repeated_segments_codec
      = pb::FieldCodec.ForMessage(18, global::ThTCHSegment.Parser);
  private readonly pbc::RepeatedField<global::ThTCHSegment> segments_ = new pbc::RepeatedField<global::ThTCHSegment>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHSegment> Segments {
    get { return segments_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHPolyline);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHPolyline other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!points_.Equals(other.points_)) return false;
    if(!segments_.Equals(other.segments_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= points_.GetHashCode();
    hash ^= segments_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    points_.WriteTo(output, _repeated_points_codec);
    segments_.WriteTo(output, _repeated_segments_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    points_.WriteTo(ref output, _repeated_points_codec);
    segments_.WriteTo(ref output, _repeated_segments_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += points_.CalculateSize(_repeated_points_codec);
    size += segments_.CalculateSize(_repeated_segments_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHPolyline other) {
    if (other == null) {
      return;
    }
    points_.Add(other.points_);
    segments_.Add(other.segments_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          points_.AddEntriesFrom(input, _repeated_points_codec);
          break;
        }
        case 18: {
          segments_.AddEntriesFrom(input, _repeated_segments_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          points_.AddEntriesFrom(ref input, _repeated_points_codec);
          break;
        }
        case 18: {
          segments_.AddEntriesFrom(ref input, _repeated_segments_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
