// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThTCHBuildingStoreyData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ThTCHBuildingStoreyData.proto</summary>
public static partial class ThTCHBuildingStoreyDataReflection {

  #region Descriptor
  /// <summary>File descriptor for ThTCHBuildingStoreyData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ThTCHBuildingStoreyDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1UaFRDSEJ1aWxkaW5nU3RvcmV5RGF0YS5wcm90bxobVGhUQ0hCdWlsdEVs",
          "ZW1lbnREYXRhLnByb3RvGhNUaFRDSFdhbGxEYXRhLnByb3RvGhNUaFRDSERv",
          "b3JEYXRhLnByb3RvGhNUaFRDSEdlb21ldHJ5LnByb3RvGhVUaFRDSFdpbmRv",
          "d0RhdGEucHJvdG8aE1RoVENIU2xhYkRhdGEucHJvdG8aFlRoVENIUmFpbGlu",
          "Z0RhdGEucHJvdG8aFlRoVENIT3BlbmluZ0RhdGEucHJvdG8ikQMKF1RoVENI",
          "QnVpbGRpbmdTdG9yZXlEYXRhEi0KDWJ1aWxkX2VsZW1lbnQYASABKAsyFi5U",
          "aFRDSEJ1aWx0RWxlbWVudERhdGESDgoGbnVtYmVyGAIgASgJEg4KBmhlaWdo",
          "dBgDIAEoARIRCgllbGV2YXRpb24YBCABKAESDQoFdXNhZ2UYBSABKAkSHQoG",
          "b3JpZ2luGAYgASgLMg0uVGhUQ0hQb2ludDNkEhgKEG1lbW9yeV9zdG9yZXlf",
          "aWQYByABKAkSJwoPbWVtb3J5X21hdHJpeDNkGAggASgLMg4uVGhUQ0hNYXRy",
          "aXgzZBIdCgV3YWxscxgJIAMoCzIOLlRoVENIV2FsbERhdGESHQoFZG9vcnMY",
          "CiADKAsyDi5UaFRDSERvb3JEYXRhEiEKB3dpbmRvd3MYCyADKAsyEC5UaFRD",
          "SFdpbmRvd0RhdGESHQoFc2xhYnMYDCADKAsyDi5UaFRDSFNsYWJEYXRhEiMK",
          "CHJhaWxpbmdzGA0gAygLMhEuVGhUQ0hSYWlsaW5nRGF0YWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ThTCHBuiltElementDataReflection.Descriptor, global::ThTCHWallDataReflection.Descriptor, global::ThTCHDoorDataReflection.Descriptor, global::ThTCHGeometryReflection.Descriptor, global::ThTCHWindowDataReflection.Descriptor, global::ThTCHSlabDataReflection.Descriptor, global::ThTCHRailingDataReflection.Descriptor, global::ThTCHOpeningDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ThTCHBuildingStoreyData), global::ThTCHBuildingStoreyData.Parser, new[]{ "BuildElement", "Number", "Height", "Elevation", "Usage", "Origin", "MemoryStoreyId", "MemoryMatrix3D", "Walls", "Doors", "Windows", "Slabs", "Railings" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ThTCHBuildingStoreyData : pb::IMessage<ThTCHBuildingStoreyData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ThTCHBuildingStoreyData> _parser = new pb::MessageParser<ThTCHBuildingStoreyData>(() => new ThTCHBuildingStoreyData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ThTCHBuildingStoreyData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ThTCHBuildingStoreyDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHBuildingStoreyData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHBuildingStoreyData(ThTCHBuildingStoreyData other) : this() {
    buildElement_ = other.buildElement_ != null ? other.buildElement_.Clone() : null;
    number_ = other.number_;
    height_ = other.height_;
    elevation_ = other.elevation_;
    usage_ = other.usage_;
    origin_ = other.origin_ != null ? other.origin_.Clone() : null;
    memoryStoreyId_ = other.memoryStoreyId_;
    memoryMatrix3D_ = other.memoryMatrix3D_ != null ? other.memoryMatrix3D_.Clone() : null;
    walls_ = other.walls_.Clone();
    doors_ = other.doors_.Clone();
    windows_ = other.windows_.Clone();
    slabs_ = other.slabs_.Clone();
    railings_ = other.railings_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ThTCHBuildingStoreyData Clone() {
    return new ThTCHBuildingStoreyData(this);
  }

  /// <summary>Field number for the "build_element" field.</summary>
  public const int BuildElementFieldNumber = 1;
  private global::ThTCHBuiltElementData buildElement_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHBuiltElementData BuildElement {
    get { return buildElement_; }
    set {
      buildElement_ = value;
    }
  }

  /// <summary>Field number for the "number" field.</summary>
  public const int NumberFieldNumber = 2;
  private string number_ = "";
  /// <summary>
  /// number
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Number {
    get { return number_; }
    set {
      number_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "height" field.</summary>
  public const int HeightFieldNumber = 3;
  private double height_;
  /// <summary>
  /// height
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Height {
    get { return height_; }
    set {
      height_ = value;
    }
  }

  /// <summary>Field number for the "elevation" field.</summary>
  public const int ElevationFieldNumber = 4;
  private double elevation_;
  /// <summary>
  /// elevation
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Elevation {
    get { return elevation_; }
    set {
      elevation_ = value;
    }
  }

  /// <summary>Field number for the "usage" field.</summary>
  public const int UsageFieldNumber = 5;
  private string usage_ = "";
  /// <summary>
  /// title block name
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Usage {
    get { return usage_; }
    set {
      usage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "origin" field.</summary>
  public const int OriginFieldNumber = 6;
  private global::ThTCHPoint3d origin_;
  /// <summary>
  /// base point
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHPoint3d Origin {
    get { return origin_; }
    set {
      origin_ = value;
    }
  }

  /// <summary>Field number for the "memory_storey_id" field.</summary>
  public const int MemoryStoreyIdFieldNumber = 7;
  private string memoryStoreyId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MemoryStoreyId {
    get { return memoryStoreyId_; }
    set {
      memoryStoreyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "memory_matrix3d" field.</summary>
  public const int MemoryMatrix3DFieldNumber = 8;
  private global::ThTCHMatrix3d memoryMatrix3D_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ThTCHMatrix3d MemoryMatrix3D {
    get { return memoryMatrix3D_; }
    set {
      memoryMatrix3D_ = value;
    }
  }

  /// <summary>Field number for the "walls" field.</summary>
  public const int WallsFieldNumber = 9;
  private static readonly pb::FieldCodec<global::ThTCHWallData> _repeated_walls_codec
      = pb::FieldCodec.ForMessage(74, global::ThTCHWallData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHWallData> walls_ = new pbc::RepeatedField<global::ThTCHWallData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHWallData> Walls {
    get { return walls_; }
  }

  /// <summary>Field number for the "doors" field.</summary>
  public const int DoorsFieldNumber = 10;
  private static readonly pb::FieldCodec<global::ThTCHDoorData> _repeated_doors_codec
      = pb::FieldCodec.ForMessage(82, global::ThTCHDoorData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHDoorData> doors_ = new pbc::RepeatedField<global::ThTCHDoorData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHDoorData> Doors {
    get { return doors_; }
  }

  /// <summary>Field number for the "windows" field.</summary>
  public const int WindowsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::ThTCHWindowData> _repeated_windows_codec
      = pb::FieldCodec.ForMessage(90, global::ThTCHWindowData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHWindowData> windows_ = new pbc::RepeatedField<global::ThTCHWindowData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHWindowData> Windows {
    get { return windows_; }
  }

  /// <summary>Field number for the "slabs" field.</summary>
  public const int SlabsFieldNumber = 12;
  private static readonly pb::FieldCodec<global::ThTCHSlabData> _repeated_slabs_codec
      = pb::FieldCodec.ForMessage(98, global::ThTCHSlabData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHSlabData> slabs_ = new pbc::RepeatedField<global::ThTCHSlabData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHSlabData> Slabs {
    get { return slabs_; }
  }

  /// <summary>Field number for the "railings" field.</summary>
  public const int RailingsFieldNumber = 13;
  private static readonly pb::FieldCodec<global::ThTCHRailingData> _repeated_railings_codec
      = pb::FieldCodec.ForMessage(106, global::ThTCHRailingData.Parser);
  private readonly pbc::RepeatedField<global::ThTCHRailingData> railings_ = new pbc::RepeatedField<global::ThTCHRailingData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ThTCHRailingData> Railings {
    get { return railings_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ThTCHBuildingStoreyData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ThTCHBuildingStoreyData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(BuildElement, other.BuildElement)) return false;
    if (Number != other.Number) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Height, other.Height)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Elevation, other.Elevation)) return false;
    if (Usage != other.Usage) return false;
    if (!object.Equals(Origin, other.Origin)) return false;
    if (MemoryStoreyId != other.MemoryStoreyId) return false;
    if (!object.Equals(MemoryMatrix3D, other.MemoryMatrix3D)) return false;
    if(!walls_.Equals(other.walls_)) return false;
    if(!doors_.Equals(other.doors_)) return false;
    if(!windows_.Equals(other.windows_)) return false;
    if(!slabs_.Equals(other.slabs_)) return false;
    if(!railings_.Equals(other.railings_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (buildElement_ != null) hash ^= BuildElement.GetHashCode();
    if (Number.Length != 0) hash ^= Number.GetHashCode();
    if (Height != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Height);
    if (Elevation != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Elevation);
    if (Usage.Length != 0) hash ^= Usage.GetHashCode();
    if (origin_ != null) hash ^= Origin.GetHashCode();
    if (MemoryStoreyId.Length != 0) hash ^= MemoryStoreyId.GetHashCode();
    if (memoryMatrix3D_ != null) hash ^= MemoryMatrix3D.GetHashCode();
    hash ^= walls_.GetHashCode();
    hash ^= doors_.GetHashCode();
    hash ^= windows_.GetHashCode();
    hash ^= slabs_.GetHashCode();
    hash ^= railings_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (buildElement_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(BuildElement);
    }
    if (Number.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Number);
    }
    if (Height != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Height);
    }
    if (Elevation != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Elevation);
    }
    if (Usage.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Usage);
    }
    if (origin_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Origin);
    }
    if (MemoryStoreyId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(MemoryStoreyId);
    }
    if (memoryMatrix3D_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(MemoryMatrix3D);
    }
    walls_.WriteTo(output, _repeated_walls_codec);
    doors_.WriteTo(output, _repeated_doors_codec);
    windows_.WriteTo(output, _repeated_windows_codec);
    slabs_.WriteTo(output, _repeated_slabs_codec);
    railings_.WriteTo(output, _repeated_railings_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (buildElement_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(BuildElement);
    }
    if (Number.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Number);
    }
    if (Height != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Height);
    }
    if (Elevation != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Elevation);
    }
    if (Usage.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Usage);
    }
    if (origin_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Origin);
    }
    if (MemoryStoreyId.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(MemoryStoreyId);
    }
    if (memoryMatrix3D_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(MemoryMatrix3D);
    }
    walls_.WriteTo(ref output, _repeated_walls_codec);
    doors_.WriteTo(ref output, _repeated_doors_codec);
    windows_.WriteTo(ref output, _repeated_windows_codec);
    slabs_.WriteTo(ref output, _repeated_slabs_codec);
    railings_.WriteTo(ref output, _repeated_railings_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (buildElement_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BuildElement);
    }
    if (Number.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Number);
    }
    if (Height != 0D) {
      size += 1 + 8;
    }
    if (Elevation != 0D) {
      size += 1 + 8;
    }
    if (Usage.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Usage);
    }
    if (origin_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Origin);
    }
    if (MemoryStoreyId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MemoryStoreyId);
    }
    if (memoryMatrix3D_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemoryMatrix3D);
    }
    size += walls_.CalculateSize(_repeated_walls_codec);
    size += doors_.CalculateSize(_repeated_doors_codec);
    size += windows_.CalculateSize(_repeated_windows_codec);
    size += slabs_.CalculateSize(_repeated_slabs_codec);
    size += railings_.CalculateSize(_repeated_railings_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ThTCHBuildingStoreyData other) {
    if (other == null) {
      return;
    }
    if (other.buildElement_ != null) {
      if (buildElement_ == null) {
        BuildElement = new global::ThTCHBuiltElementData();
      }
      BuildElement.MergeFrom(other.BuildElement);
    }
    if (other.Number.Length != 0) {
      Number = other.Number;
    }
    if (other.Height != 0D) {
      Height = other.Height;
    }
    if (other.Elevation != 0D) {
      Elevation = other.Elevation;
    }
    if (other.Usage.Length != 0) {
      Usage = other.Usage;
    }
    if (other.origin_ != null) {
      if (origin_ == null) {
        Origin = new global::ThTCHPoint3d();
      }
      Origin.MergeFrom(other.Origin);
    }
    if (other.MemoryStoreyId.Length != 0) {
      MemoryStoreyId = other.MemoryStoreyId;
    }
    if (other.memoryMatrix3D_ != null) {
      if (memoryMatrix3D_ == null) {
        MemoryMatrix3D = new global::ThTCHMatrix3d();
      }
      MemoryMatrix3D.MergeFrom(other.MemoryMatrix3D);
    }
    walls_.Add(other.walls_);
    doors_.Add(other.doors_);
    windows_.Add(other.windows_);
    slabs_.Add(other.slabs_);
    railings_.Add(other.railings_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (buildElement_ == null) {
            BuildElement = new global::ThTCHBuiltElementData();
          }
          input.ReadMessage(BuildElement);
          break;
        }
        case 18: {
          Number = input.ReadString();
          break;
        }
        case 25: {
          Height = input.ReadDouble();
          break;
        }
        case 33: {
          Elevation = input.ReadDouble();
          break;
        }
        case 42: {
          Usage = input.ReadString();
          break;
        }
        case 50: {
          if (origin_ == null) {
            Origin = new global::ThTCHPoint3d();
          }
          input.ReadMessage(Origin);
          break;
        }
        case 58: {
          MemoryStoreyId = input.ReadString();
          break;
        }
        case 66: {
          if (memoryMatrix3D_ == null) {
            MemoryMatrix3D = new global::ThTCHMatrix3d();
          }
          input.ReadMessage(MemoryMatrix3D);
          break;
        }
        case 74: {
          walls_.AddEntriesFrom(input, _repeated_walls_codec);
          break;
        }
        case 82: {
          doors_.AddEntriesFrom(input, _repeated_doors_codec);
          break;
        }
        case 90: {
          windows_.AddEntriesFrom(input, _repeated_windows_codec);
          break;
        }
        case 98: {
          slabs_.AddEntriesFrom(input, _repeated_slabs_codec);
          break;
        }
        case 106: {
          railings_.AddEntriesFrom(input, _repeated_railings_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (buildElement_ == null) {
            BuildElement = new global::ThTCHBuiltElementData();
          }
          input.ReadMessage(BuildElement);
          break;
        }
        case 18: {
          Number = input.ReadString();
          break;
        }
        case 25: {
          Height = input.ReadDouble();
          break;
        }
        case 33: {
          Elevation = input.ReadDouble();
          break;
        }
        case 42: {
          Usage = input.ReadString();
          break;
        }
        case 50: {
          if (origin_ == null) {
            Origin = new global::ThTCHPoint3d();
          }
          input.ReadMessage(Origin);
          break;
        }
        case 58: {
          MemoryStoreyId = input.ReadString();
          break;
        }
        case 66: {
          if (memoryMatrix3D_ == null) {
            MemoryMatrix3D = new global::ThTCHMatrix3d();
          }
          input.ReadMessage(MemoryMatrix3D);
          break;
        }
        case 74: {
          walls_.AddEntriesFrom(ref input, _repeated_walls_codec);
          break;
        }
        case 82: {
          doors_.AddEntriesFrom(ref input, _repeated_doors_codec);
          break;
        }
        case 90: {
          windows_.AddEntriesFrom(ref input, _repeated_windows_codec);
          break;
        }
        case 98: {
          slabs_.AddEntriesFrom(ref input, _repeated_slabs_codec);
          break;
        }
        case 106: {
          railings_.AddEntriesFrom(ref input, _repeated_railings_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
